// Generated by build script, do not edit!
#ifndef RC_INVOKED
#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies ApS";
    extern const char* const UnityCopyright = "(c) 2021 Unity Technologies ApS. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/buildslave/unity/build";

    extern const char* const UnityVersion = "2021.2.7f1";
    extern const char* const UnityVersionDigits = "2021.2.7";
    extern const char* const UnityVersionSuffix = "f1";
    extern const UInt32 UnityVersionVer = 2021;
    extern const UInt32 UnityVersionMajor = 2;
    extern const UInt32 UnityVersionMinor = 7;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2021.2.7f1_6bd9e232123f";
    extern const char* const UnityVersionUnderHash_Verbose = "2021.2.7f1_6bd9e232123f";
    extern const char* const UnityVersionUnderHash_WithParens = "2021.2.7f1 (6bd9e232123f)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 7068130;

    extern const UInt64 UnityVersionDate = 1639204015;
    extern const char* const UnityVersionBranch = "2021.2/staging";
    extern const char* const UnityVersionDisplay = "2021.2.7f1";
    extern const char* const UnityVersionDisplay_Verbose = "2021.2.7f1.4128";
    extern const char* const UnityVersionRevision = "6bd9e232123f";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2021.2.7f1 (6bd9e232123f)";
    extern const wchar_t* const L_UnityVersion = L"2021.2.7f1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies ApS"
    #define UNITY_COPYRIGHT "(c) 2021 Unity Technologies ApS. All rights reserved."
    #define UNITY_VERSION_VER 2021
    #define UNITY_VERSION_MAJ 2
    #define UNITY_VERSION_MIN 7
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2021.2.7f1_6bd9e232123f"
    #define UNITY_VERSION_PARENS_HASH "2021.2.7f1 (6bd9e232123f)"
    #define UNITY_VERSION_BLD 7068130
    #define UNITY_VERSION_WIN "2021.2.7.7068130"

#endif // !RC_INVOKED
